version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
  exclusions:
    paths:
      - ui/node_modules

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
