coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 85%
        threshold: 0%

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: go
      paths:
        - "!ui/"
    - name: ui
      paths:
        - "ui/src/"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "internal/web/dist"
  - "cmd/pando"
  - "**/*_test.go"
  - "ui/node_modules"
  - "ui/e2e"
